requires "Kossy", 0.38;
requires "DBIx::Sunny";

requires "DBD::Pg";
requires "Starman";
requires "Plack::Session";
requires "Furl";
requires "IO::Socket::SSL";
requires "String::Util";

requires "Gazelle";
requires "Guard";
requires "Plack::Middleware::Static::OpenFileCache";
requires "URL::Encode::XS";
requires "Plack::Middleware::Session::Simple";
requires "Proclet";
requires "Text::Markdown::Hoedown";
requires "Devel::NYTProf";
requires "Redis::Fast";
requires "Cache::Memcached::Fast";
requires "Sereal";
requires "Cache::FastMmap";
requires "Redis::Jet";
requires "Data::Section::Simple";
requires "Cookie::Baker::XS";
requires "WWW::Form::UrlEncoded::XS";
requires "Digest::SHA";

